wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
import os.path

from flask import Blueprint, jsonify, session, send_file
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user
from werkzeug.utils import secure_filename

from wiki.core import Processor
from wiki.web import current_users, user
from wiki.web import current_wiki
from wiki.web.forms import EditorForm, SignUpForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web.user import *

bp = Blueprint('wiki', __name__, static_folder='static', static_url_path='/static')
img = os.path.join(bp.static_folder, 'Images')


ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg'}


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@bp.route('/')
@protect
def home():
    user_name = session["unique_id"]
    if User.is_authenticated:
        page = current_wiki.get(user_name + '-' + 'home')
        if page:
            return display(user_name + '-' + 'home')
        return render_template('home.html')
    return redirect(url_for('user_login'))


@bp.route('/index/')
@protect
def index():
    pages = current_wiki.index()
    return render_template('index.html', pages=pages)


# function used to display profile page
@bp.route('/profile')
@protect
def profile():
    user_name = session["unique_id"]
    all_pages = current_wiki.get_all()
    bio_page = current_wiki.get(user_name + '-' +'bio')
    if bio_page:
        return display(user_name + '-' + 'bio', pages_sent_by_author=all_pages)
    return render_template('bio.html')


@bp.route('/<path:url>/')
@protect
def display(url, pages_sent_by_author=None):
    page = current_wiki.get_or_404(url)

    user_name = session["unique_id"]
    file_extension = search_file_in_directory(img, url)

    if file_extension:
        page_image = f"{url}{file_extension}"
    else:
        page_image = ''

    if url == 'home':
        return render_template('page.html', page=page, image=page_image)
    elif url == user_name + '-bio':
        page_bio = current_wiki.get_or_404(url)
        pages_sent_by_author = current_wiki.get_all()
        return render_template('page_bio.html', page=page_bio, pages_sent=pages_sent_by_author, image=page_image)
    return render_template('page.html', page=page, image=page_image)


@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


def search_file_in_directory(directory, filename):
    for root, dirs, files in os.walk(directory):
        for file in files:
            # Compare filenames without extensions
            if os.path.splitext(file)[0] == os.path.splitext(filename)[0]:
                file_extension = os.path.splitext(file)[1]
                return file_extension
    return None


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)

    file_extension = search_file_in_directory(img, url)

    if file_extension:
        page_image = f"{url}{file_extension}"
    else:
        page_image = ''

    if not page:
        page = current_wiki.get_bare(url)

    form = EditorForm(obj=page)

    # Initialize form with page data
    if form.validate_on_submit():
        form.populate_obj(page)

        upload_image = form.image.data
        if upload_image and allowed_file(upload_image.filename):
            file = upload_image

            original_file_name = secure_filename(file.filename)
            file_extension = original_file_name.split('.', 1)[-1]
            new_file_name = f"{url}.{file_extension}"

            file.save(os.path.join(img, new_file_name))
            flash('Image uploaded successfully!', 'success')
        elif upload_image is None:
            pass
        else:
            flash('Invalid file type. Allowed types are png, jpg, jpeg.', 'error')

        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page, image=page_image)



@bp.route('/save/<path:url>/', methods=['POST'])
@protect
def save(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)

    if request.method == 'POST':
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        return jsonify(success=True)
    return jsonify("success=False, errors=form.errors")


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        new_url = form.url.data
        current_wiki.move(url, new_url)

        file_extension = search_file_in_directory(img, url)

        if file_extension:
            old_image_path = os.path.join(img,f"{url}{file_extension}")
            new_image_path = os.path.join(img,f"{new_url}{file_extension}")

            os.rename(old_image_path, new_image_path)

        return redirect(url_for('wiki.display', url=new_url))
    return render_template('move.html', form=form, page=page)


@bp.route('/download_image/<path:url>/')
@protect
def download_image(url):
    user_name = session["unique_id"]

    file_extension = search_file_in_directory(img, url)


    page_image = f"{url}{file_extension}"

    image_path = os.path.join(img, page_image)


    # Set the filename that the user will see when downloading
    filename = page_image

    return send_file(image_path, as_attachment=True, download_name=filename)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    form = SearchForm()
    if form.validate_on_submit():
        if form.search_by_author.data:

            results = current_wiki.search_by_author(form.term.data)
        else:
            results = current_wiki.search(form.term.data, form.ignore_case.data)

        return render_template('search.html', form=form,
                               results=results, search=form.term.data)
    return render_template('search.html', form=form, search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        session["unique_id"] = form.name.data
        login_user(user)
        user.set('authenticated', True)
        session['is_authenticated'] = True
        flash(f'Login successful, {form.name.data}!', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignUpForm()
    if form.validate_on_submit():
        if form.password.data == form.confirm_password.data:
            user_manager = UserManager()
            # Check if the username already exists
            if user_manager.user_exists(form.name.data):
                flash('Username already exists. Please choose a different username.', 'danger')
            else:
                user_manager.add_user(form.name.data, form.password.data)

                flash('Account created successfully. You can now log in.', 'success')
                return redirect(url_for('wiki.user_login'))
    return render_template('signup.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    session['is_authenticated'] = False
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    return render_template('signup.html')


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='responsive.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='custom.css') }}">
        <script src="https://kit.fontawesome.com/b6798fcdf3.js" crossorigin="anonymous"></script>
	</head>

	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<div class="row">
						<div class="span12">
							<a href="#" class="brand"><img src= "{{ url_for('wiki.static', filename='Images/' + 'RikiPDYea Logo.png') }}" alt="img"></a>
							<ul class="nav">
								<li><a href="{{ url_for('wiki.home') }}">Home</a></li>
								<li><a href="{{ url_for('wiki.index') }}">Index</a></li>
								<li><a href="{{ url_for('wiki.tags') }}">Tags</a></li>
								<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
                                <li><a href="{{ url_for('wiki.profile') }}">Profile</a></li>
								<li class="divider-vertical"></li>
								<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
								<li><div id="google_translate_element"></div></li>
								<li class="divider-vertical"></li>
								<li></li>
							</ul>

							<ul class="nav pull-right">
                            {% if not session['is_authenticated'] %}
                                <li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
                            {% else %}
                                <li><a href="{{ url_for('wiki.user_logout') }}">Logout</a></li>
                            {% endif %}
                             </ul>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="span10 offset1">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="span7 offset1">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
								<div class="alert alert-{{ category }}">
									<button type="button" class="close" data-dismiss="alert">&times;</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error">
							<p>Errors occurred verifying your input. Please check the marked fields below:</p>
							<ul>
								{% for field, errors in form.errors.items() %}
									<li>{{ field }}: {{ ', '.join(errors) }}</li>
								{% endfor %}
							</ul>
						</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
				<div class="span3">
					{% block sidebar %}
					{% endblock sidebar %}
				</div>
			</div>
		</div>

        <script async defer src="https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
        <script>
        function googleTranslateElementInit() {
            new google.translate.TranslateElement(
            {pageLanguage: 'en'},
            'google_translate_element'
            );
        }
        </script>
		<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.9.0/jquery.min.js "></script>
		<script type="text/javascript">
			if (typeof jQuery == 'undefined') {
				document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
			}
		</script>
		<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
		<script type="text/javascript">
			{% block postscripts %}
			{% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/bio.html
{% extends "base.html" %}
{% block title %}
    Welcome to Your New Wiki - Share Your Professional Journey {{ session.get('unique_id', 'Default Title') }}
{% endblock title %}

{% block content %}
<p>Your professional biography is currently missing. We highly recommend completing it to enhance your profile.</p>
<p><a href="{{ url_for('wiki.edit', url=session.get('unique_id') + '-bio') }}" class="btn btn-success">Compose Your Biography</a></p>

    {% if pages_sent %}
    <h3>Posts Created</h3> <!-- Add this line for the heading above the table -->
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>URL</th>
            </tr>
        </thead>
        <tbody>
            {% for page in pages_sent %}
                <tr>
                    <td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
                    <td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
{% endif %}
{% endblock %}

wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Create a new page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
	{{ form.hidden_tag() }}
	{{ input(form.url, placeholder="URL of the new page", autocomplete="off") }}
	<input type="submit" class="btn btn-success" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Thank you for creating new content!</p>
{% endblock sidebar %}

wiki/web/templates/editor.html
{% extends "base.html" %}

{% block title -%}
Wiki Editor
{%- endblock title %}

{% block content %}
<ul class="nav nav-tabs">
	<li class="active"><a href="#editor" data-toggle="tab">Editor</a></li>
	<li><a href="#preview" data-toggle="tab" id="previewlink">Preview</a></li>
    <li class="pull-right"><span class="msg-view"></span></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="editor">
		<form method="post" class="form" enctype="multipart/form-data">
			{{ form.hidden_tag() }}
			{{ input(form.title, placeholder="Title", class="span7", autocomplete="off") }}
			{{ input(form.content, placeholder="Markdown", class="span7", rows="20") }}
			{{ input(form.tags, placeholder="Tags (comma separated)", class="span7", autocomplete="off") }}

            {% if image != '' %}
                <p><b>Upload to update the image.</b></p>
            {% else %}
                <p><b>Upload to add an image.</b></p>
            {% endif %}
            {{ input(form.image, placeholder="Upload to add/Update the image", type="file") }}
			<div class="form-actions">
        <div class="pull-left">
          <a class="btn" href="#preview" id="previewbtn">Preview</a>
        </div>
				<div class="pull-right">
          <a class="btn" href="{{ url_for('wiki.display', url=page.url) }}">Cancel</a>
					<button class="btn btn-success" type="submit">Save</button>
				</div>
			</div>
		</form>
	</div>
	<div class="tab-pane" id="preview"></div>
</div>
{% endblock content %}

{% block sidebar %}
{% if image != '' %}
    <img src= "{{ url_for('wiki.static', filename='Images/' + image) }}" alt="img">
{% endif %}
<h3>Editor How-To</h3>
<p>This editor is <a href="http://daringfireball.net/projects/markdown/">markdown</a> featured.</p>
<pre><code>* I
* am
* a
* list</code></pre>
Turns into:
<ul>
<li>I</li>
<li>am</li>
<li>a</li>
<li>list</li>
</ul>
<p><code>**bold** and *italics*</code> turn into <strong>bold</strong> and <em>italics</em>. Very easy!</p>
<p>Create links with <code>[NoTube](http://www.notube.com)</code>. They turn into <a href="http://www.notube.com">NoTube</a>.</p>
<p>Headers are as follows:</p>
<pre><code># Level 1
## Level 2
### Level 3</code></pre>
<p></p>

{% endblock sidebar %}

{% block postscripts -%}
{{ super() }}

$(document).ready(function() {
    var inputElement = $('input[type="text"], textarea');
    var textareaValue = inputElement.filter('textarea').val();
    var isCreatePage = textareaValue.trim() === '';

    console.log(isCreatePage);

    var thisUrl = window.location.pathname.split('/')[2];
    var msgView = document.querySelector('.msg-view');
    var saveTimeout;
    var saveClicked = false;

    if (!isCreatePage) {
      inputElement.on('input', function() {
        msgView.innerHTML = 'Unsaved changes •';
        clearTimeout(saveTimeout);

        saveTimeout = setTimeout(function() {
          var formData = new FormData($('.form')[0]);

          $.ajax({
            url: `/save/${thisUrl}`,
            type: "POST",
            data: formData,
            processData: false,
            contentType: false,
            success: function(msg) {
              console.log(msg);
              msgView.innerHTML = 'Saved';
            },
            error: function(msg) {
              console.error(msg);
              msgView.innerHTML = 'Error';
            },
            complete: function() {
              console.log('Completed!');
            }
          });
        }, 1000);
      });
    } else {
      console.log('isCreatePage');
      var unsavedChanges = false;
      console.log('unsavedChanges', unsavedChanges);

      inputElement.on('input', function() {
        unsavedChanges = true;
      });

      window.onbeforeunload = function(event) {
        if (unsavedChanges && !saveClicked) {
          return "You have unsaved changes. Are you sure you want to leave?";
        }
      };
    }
    $('.btn-success').on('click', function() {
      saveClicked = true;
    });
});


$('#previewlink').on('click', function() {
	var $form = $('.form');
  var $inputs = $form.find('input, textarea, button');
  var $pre = $('#preview');
  var bodycontent = 'title: preview\n\n' + $form.find('textarea').val();
  $inputs.prop('disabled', true);
  $pre.removeClass('alert').removeClass('alert-error').html("Loading...");
  $.ajax({
    url: "{{ url_for('wiki.preview') }}",
    type: "POST",
    data: { body: bodycontent },
    success: function(msg) {
      $pre.html(msg);
      console.log(msg);
    },
    error: function() {
			$pre.addClass('alert').addClass('alert-error');
      $pre.html('There was a problem with the preview.');
    },
    complete: function() {
      $inputs.prop('disabled', false);
    }
  });
});
$('#previewbtn').on('click', function(event) {
	event.preventDefault();
	$('#previewlink').click();
});
{%- endblock postscripts %}

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="control-group {% if field.errors %}error{% endif %}">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<label for="{{ field.name }}" class="checkbox">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-inline">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url=session.get('unique_id') + '-home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.create') }}">New Page</a></li>
	<li><a href="{{ url_for('wiki.tags') }}">Tag List</a></li>
	<li><a href="{{ url_for('wiki.search') }}">Search</a></li>
</ul>
{% endblock sidebar %}

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success" value="Move">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}
	{{ page.title }}
{% endblock title %}


{% block content %}
  <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
    <div class="modal-header">
      <h3>Are you sure?</h3>
    </div>
    <div class="modal-body">
      <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
      <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
    </div>
  </div>
	{{ page }}
     <div id="loading-spinner" class="text-center">
        <i class="fas fa-spinner fa-spin fa-2x"></i>
        <h3 class="display-inline">Loading...</h3>
    </div>

{% endblock content %}

{% block sidebar %}
{% if page.tags %}
<h3>Tags</h3>
  <ul>
      {% for tag in page.tags.split(',') %}
        <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}
{% if image != '' %}
<img src= "{{ url_for('wiki.static', filename='Images/' + image) }}" alt="img">
{% endif %}
<h3>Actions</h3>
<ul class="nav nav-tabs nav-stacked">
	<li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
  <li><a href="{{ url_for('wiki.move', url=page.url) }}">Move</a></li>
    {%  if image != '' %}
    <li><a href="{{ url_for('wiki.download_image', url=page.url) }}" data-toggle="modal">Download Image</a></li>
    {%  endif %}
  <li><a href="#confirmDelete" data-toggle="modal" class="text-error">Delete</a></li>
</ul>

{% endblock sidebar %}

wiki/web/templates/page_bio.html
{% extends "base.html" %}

{% block title %}
    Biography
{% endblock title %}

{% block content %}
    <div id="confirmDelete" class="modal hide fade" aria-hidden="true">
        <div class="modal-header">
            <h3>Are you sure?</h3>
        </div>
        <div class="modal-body">
            <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
        </div>
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal" aria-hidden="true">No</a>
            <a href="{{ url_for('wiki.delete', url=page.url) }}" class="btn btn-danger">Yes, delete.</a>
        </div>
    </div>

    {{ page }}

    <!-- New Code Starts Here -->
    <hr>
    <h3>Posts Created</h3> <!-- Heading above the table -->
    {% if pages_sent %}
    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>URL</th>
            </tr>
        </thead>
        <tbody>
            {% for page in pages_sent %}
                {% if page.url != session.get('unique_id', 'Default Title') + "-home" and page.url != session.get('unique_id', 'Default Title') + "-bio" %}
                    <tr>
                        <td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
                        <td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <p>There are no pages yet.</p>
    {% endif %}
    <hr>
    <!-- New Code Ends Here -->
{% endblock content %}

{% block sidebar %}
{% if image != '' %}
    <img src= "{{ url_for('wiki.static', filename='Images/' + image) }}" alt="img">
{% endif %}

    {% if page.tags %}
    <h3>Tags</h3>
    <ul>
        {% for tag in page.tags.split(',') %}
            <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
        {% endfor %}
    </ul>
    {% endif %}
    <h3>Actions</h3>
    <ul class="nav nav-tabs nav-stacked">
        <li><a href="{{ url_for('wiki.edit', url=page.url) }}">Edit</a></li>
    </ul>
{% endblock sidebar %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
<div class="row">
	<div class="span8 offset1">
		<form class="form-inline well" method="POST">
			{{ form.hidden_tag() }}
			{{ form.term(placeholder='Search for.. (regex accepted)', autocomplete="off") }}
            {{ form.ignore_case() }} Ignore Case
            {{ form.search_by_author() }} Search by Author's Name only
			<input type="submit" class="btn btn-success pull-right" value="Search!">
		</form>
	</div>
</div>

{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
					<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/signup.html
{% extends "base.html" %}

{% block title %}User Registration{% endblock title %}

{% block content %}
    <form class="vertical-form" method="POST">
        {{ form.hidden_tag() }}
        {{ form.name(placeholder='Username') }}
        {{ form.password(placeholder='Password') }}
        {{ form.confirm_password(placeholder='Confirm Password') }}
        <input type="submit" class="btn-primary small-btn" value="Sign Up">
    </form>


{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}